name: FrameworkDetector Publish

trigger: none
pr: none

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-latest
        os: windows
    stages:
    - stage: BuildStage
      jobs:
      - job: BuildFrameworkDetectorNuGetsJob
        displayName: Build FrameworkDetector NuGets
        pool:
          name: Azure-Pipelines-1ESPT-ExDShared
          image: windows-latest
          os: windows
          hostArchitecture: amd64

        steps:
          - checkout: self
          - task: UseDotNet@2
            displayName: Setup .NET 10
            inputs:
              version: 10.0.x
          - task: NuGetAuthenticate@1
            displayName: NuGet Authentication for ADO
          - pwsh: |
              ./scripts/build-nuget-release.ps1 -OutputRoot "$(Build.StagingDirectory)\FrameworkDetector.NuGet"
            displayName: Build FrameworkDetector NuGets

        templateContext:
            outputs:
              - output: pipelineArtifact
                displayName: 'Upload FrameworkDetector NuGets to Pipeline Artifacts'
                artifactName: FrameworkDetector.NuGet
                targetPath: $(Build.StagingDirectory)\FrameworkDetector.NuGet
      - job: BuildFrameworkDetectorCliJob
        displayName: Build FrameworkDetector.CLI (Self-Contained)
        pool:
          name: Azure-Pipelines-1ESPT-ExDShared
          image: windows-latest
          os: windows
          hostArchitecture: amd64

        steps:
          - checkout: self
          - task: UseDotNet@2
            displayName: Setup .NET 10
            inputs:
              version: 10.0.x
          - task: NuGetAuthenticate@1
            displayName: NuGet Authentication for ADO
          - pwsh: |
              ./scripts/build-cli-release.ps1 -OutputRoot "$(Build.StagingDirectory)\FrameworkDetector.CLI"
            displayName: Build FrameworkDetector CLI

        templateContext:
            outputs:
              - output: pipelineArtifact
                displayName: 'Upload FrameworkDetector CLI to Pipeline Artifacts'
                artifactName: FrameworkDetector.CLI
                targetPath: $(Build.StagingDirectory)\FrameworkDetector.CLI
    - stage: PublishStage
      dependsOn: BuildStage
      jobs:
      - job: PublishFrameworkDetectorNuGetsToInternalAdoJob
        displayName: Publish FrameworkDetector NuGets to ADO
        pool:
          name: Azure-Pipelines-1ESPT-ExDShared
          image: windows-latest
          os: windows
          hostArchitecture: amd64
        templateContext:
            type: releaseJob
            isProduction: false
            inputs:
            - input: pipelineArtifact
              artifactName: FrameworkDetector.NuGet
              targetPath: '$(Pipeline.Workspace)/FrameworkDetector.NuGet'
        steps:
        - checkout: none
        - task: NuGetToolInstaller@1
          displayName: 'Use NuGet '
        - task: NuGetAuthenticate@1
          displayName: NuGet Authentication for ADO
        - pwsh: |
              nuget.exe push *.nupkg -ApiKey AzureArtifacts -Source $(INTERNAL_PUBLISH_AZURE_ARTIFACTS_FEED) -NonInteractive -Verbosity Detailed -SkipDuplicate -NoSymbols
          displayName: NuGet Push to ADO
          workingDirectory: '$(Pipeline.Workspace)/FrameworkDetector.NuGet'
